debug: true

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: ipedrazas/dind
    tag:
      - latest
      - "$$BUILD_NUMBER"
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    when:
      branch: master
